"""WAF (Web Application Firewall) detector.

Fingerprints WAFs via HTTP response headers, cookies, and response body
patterns. Covers: Cloudflare, AWS WAF, Akamai, Sucuri, ModSecurity,
Imperva, F5 BIG-IP, Barracuda, and more.
"""

import asyncio
import json
import logging
import random

import aiohttp
from colorama import Fore, Style
from tqdm import tqdm

from vortex.utils import stop_event, display_banner
from vortex.user_agents import USER_AGENTS

# WAF fingerprint signatures: (waf_name, check_function)
# Each check function takes (headers_dict, cookies_dict, body_str) -> bool
_WAF_SIGNATURES: list[tuple[str, object]] = [
    (
        "Cloudflare",
        lambda h, c, b: (
            "cf-ray" in h
            or "cloudflare" in h.get("server", "").lower()
            or "__cflb" in c
            or "cloudflare" in b.lower()
            or "attention required! | cloudflare" in b.lower()
        ),
    ),
    (
        "AWS WAF",
        lambda h, c, b: (
            "awswaf" in str(c).lower()
            or "x-amzn-requestid" in h
            or "x-amz-cf-id" in h
            or "aws" in h.get("x-powered-by", "").lower()
        ),
    ),
    (
        "Akamai",
        lambda h, c, b: (
            "akamai" in h.get("server", "").lower()
            or "x-akamai-transformed" in h
            or "akamaierror" in b.lower()
            or "reference #" in b.lower() and "akamai" in b.lower()
        ),
    ),
    (
        "Sucuri",
        lambda h, c, b: (
            "sucuri" in h.get("server", "").lower()
            or "x-sucuri-id" in h
            or "sucuri" in b.lower()
            or "access denied - sucuri" in b.lower()
        ),
    ),
    (
        "ModSecurity",
        lambda h, c, b: (
            "mod_security" in b.lower()
            or "modsecurity" in b.lower()
            or "not acceptable!" in b.lower() and "server" in b.lower()
        ),
    ),
    (
        "Imperva / Incapsula",
        lambda h, c, b: (
            "incap_ses" in str(c).lower()
            or "visid_incap" in str(c).lower()
            or "x-iinfo" in h
            or "incapsula" in b.lower()
            or "imperva" in b.lower()
        ),
    ),
    (
        "F5 BIG-IP ASM",
        lambda h, c, b: (
            "ts" in str(c).lower() and len(str(c)) > 20
            or "bigip" in h.get("server", "").lower()
            or "f5" in h.get("server", "").lower()
            or "the requested url was rejected" in b.lower()
        ),
    ),
    (
        "Barracuda WAF",
        lambda h, c, b: (
            "barra_counter_session" in str(c).lower()
            or "barracuda" in b.lower()
        ),
    ),
    (
        "Fortinet FortiWeb",
        lambda h, c, b: (
            "fortiwafsid" in str(c).lower()
            or "fortiweb" in h.get("server", "").lower()
            or "fortigate" in b.lower()
        ),
    ),
    (
        "Citrix NetScaler",
        lambda h, c, b: (
            "ns_af" in str(c).lower()
            or "citrixns" in str(c).lower()
            or "netscaler" in h.get("via", "").lower()
        ),
    ),
    (
        "Radware AppWall",
        lambda h, c, b: (
            "x-sl-compstate" in h
            or "radware" in b.lower()
        ),
    ),
    (
        "Wallarm",
        lambda h, c, b: (
            "wallarm" in b.lower()
            or "x-wallarm-node" in h
        ),
    ),
    (
        "Wordfence",
        lambda h, c, b: (
            "wordfence" in b.lower()
            or "generated by wordfence" in b.lower()
        ),
    ),
    (
        "Fastly",
        lambda h, c, b: (
            "fastly" in h.get("via", "").lower()
            or "x-fastly-request-id" in h
            or "fastly-error" in h
        ),
    ),
    (
        "Varnish",
        lambda h, c, b: (
            "varnish" in h.get("x-cache", "").lower()
            or "varnish" in h.get("via", "").lower()
            or "x-varnish" in h
        ),
    ),
]

# Probe payload to trigger WAF (common XSS/SQLi patterns)
_PROBE_PAYLOAD = "?__vx_probe=<script>alert(1)</script>&id=1' OR '1'='1"


async def _detect_waf(
    session,
    url: str,
    proxy=None,
    timeout: float = 10,
    random_ua: bool = False,
) -> dict:
    """Probe a URL and return WAF detection results."""
    req_kwargs = {}
    if proxy:
        req_kwargs["proxy"] = proxy

    headers = {"User-Agent": random.choice(USER_AGENTS) if random_ua else "Mozilla/5.0"}

    result = {
        "url": url,
        "waf": None,
        "waf_detected": False,
        "evidence": [],
    }

    # First probe: normal request to get baseline headers
    probe_url = url.rstrip("/") + _PROBE_PAYLOAD
    try:
        async with session.get(
            probe_url,
            headers=headers,
            timeout=aiohttp.ClientTimeout(total=timeout),
            allow_redirects=True,
            **req_kwargs,
        ) as resp:
            resp_headers = {k.lower(): v for k, v in resp.headers.items()}
            cookies = {k: v for k, v in resp.cookies.items()}
            try:
                body = await resp.text(errors="replace")
            except Exception:
                body = ""

            detected_wafs = []
            for waf_name, check_fn in _WAF_SIGNATURES:
                try:
                    if check_fn(resp_headers, cookies, body):
                        detected_wafs.append(waf_name)
                except Exception:
                    pass

            if detected_wafs:
                result["waf_detected"] = True
                result["waf"] = detected_wafs[0] if len(detected_wafs) == 1 else detected_wafs
                result["evidence"] = detected_wafs
                result["status"] = resp.status
            else:
                result["status"] = resp.status

    except Exception as exc:
        logging.debug(f"WAF detection error for {url}: {exc}")
        result["error"] = str(exc)

    return result


async def detect_waf(
    urls,
    output_file=None,
    output_format="txt",
    proxy=None,
    timeout: float = 10,
    random_ua: bool = False,
    rate_limit=None,
    max_threads: int = 20,
):
    """Detect WAFs for the given *urls*.

    Parameters
    ----------
    urls : list[str]
        Target URLs to probe.
    output_file : str or None
        Path to write results.
    output_format : str
        ``'json'`` or ``'txt'``.

    Returns
    -------
    list[dict]
        WAF detection results (one per URL).
    """
    display_banner()
    print(
        f"{Fore.CYAN}[*] Detecting WAF for {len(urls)} URL(s) "
        f"({len(_WAF_SIGNATURES)} WAF signatures)...{Style.RESET_ALL}"
    )

    all_results: list[dict] = []
    sem = asyncio.Semaphore(max_threads)

    async def handle(url, pbar):
        if stop_event.is_set():
            pbar.update(1)
            return
        async with sem:
            async with aiohttp.ClientSession(
                connector=aiohttp.TCPConnector(ssl=False)
            ) as session:
                result = await _detect_waf(session, url, proxy, timeout, random_ua)
                if result["waf_detected"]:
                    wafs = result["waf"]
                    waf_str = ", ".join(wafs) if isinstance(wafs, list) else wafs
                    tqdm.write(
                        f"{Fore.YELLOW}[!] WAF Detected: {url} | WAF={waf_str}{Style.RESET_ALL}"
                    )
                else:
                    tqdm.write(
                        f"{Fore.GREEN}[✔] No WAF detected: {url}{Style.RESET_ALL}"
                    )
                all_results.append(result)
            if rate_limit:
                await asyncio.sleep(1.0 / rate_limit)
        pbar.update(1)

    with tqdm(total=len(urls), desc="WAF Detection", ncols=80) as pbar:
        await asyncio.gather(*[handle(u, pbar) for u in urls])

    waf_count = sum(1 for r in all_results if r["waf_detected"])
    print(
        f"{Fore.CYAN}[✔] WAF detection complete — "
        f"{waf_count}/{len(all_results)} URL(s) protected by a WAF.{Style.RESET_ALL}"
    )

    if output_file and all_results:
        with open(output_file, "w", encoding="utf-8") as fh:
            if output_format == "json":
                json.dump(all_results, fh, indent=2)
            else:
                for r in all_results:
                    waf_str = str(r.get("waf") or "None")
                    fh.write(f"{r['url']} | WAF={waf_str} | detected={r['waf_detected']}\n")

    return all_results
